### ISSUE TITLE
injectable_generator not work anymore on Flutter 1.20

### ISSUE THREAD

**Issue by gloryluu** [Milad-Akarie/injectable#119]
Today, after upgrade Flutter to 1.20, I cannot generate the injector anymore.

```
[SEVERE] injectable_generator:injectable_builder on lib/main.dart:

Bad state: Unexpected diagnostics:
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:119:41 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:152:17 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:88:62 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:153:38 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:186:51 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:133:32 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:154:25 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:18:17 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:64:4 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:168:32 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:47:14 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:159:38 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:132:37 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:118:48 - This requires the 'non-nullable' language feature to be enabled.
/Users/quang.luu/Library/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:19:11 - This requires the 'non-nullable' language feature to be enabled.
```

**Comment by gloryluu** [comment]
Updated: I have found some workarounds on this issue:
Add analyzer: 0.39.14 In pubspec
Add parameter --enable-experiment=non-nullable

**Comment by FakenMaster** [comment]
[flutter issue #62240](https://github.com/flutter/flutter/issues/62240#issuecomment-663978057)

**Comment by Milad-Akarie** [comment]
looks like it was fixed by just setting analyzer version to  ^0.39.14

**Comment by onats1** [comment]
Still having this issue. Injectable doesn't generate the init file after running build_runner.
