### ISSUE TITLE
Is Injectable unable to detect dependencies from micropackages

### ISSUE THREAD

**Issue by tomwyr** [Milad-Akarie/injectable#341]
I have a simple di setup:
- package A declares `InjectableInit` and depends on package B
- package B declares `InjectableInit.microPackage`

Consider following dependency configuration:
```Dart
// package B / service.dart

abstract class Service {}

@Injectable(as: Service)
class ServiceImpl implements Service {}
```
```Dart
// package B / service_library.dart

export 'src/service.dart';
```
```Dart
// package A / controller.dart

import 'package:injectable/injectable.dart';
import 'package:service_library/service_library.dart';

@Injectable()
class Controller {
  Controller({
    required this.service,
  });

  final Service service;
}

```
Whenever I run build runner, I get the following warning:
```
[WARNING] injectable_generator:injectable_config_builder on lib/injectable.dart:
Missing dependencies in test_injectable/injectable.dart

[Controller] depends on unregistered type [Service] from package:service_library/service_library.dart

Did you forget to annotate the above class(s) or their implementation with @injectable? 
or add the right environment keys?
------------------------------------------------------------------------ 
```
With the micropackages support recently added to Injectable, wouldn't the generator know that `Service` was registered by `service_library` based on the static analysis of code?

**Comment by Hwan-seok** [comment]
I got the same warning.
In my case, the abstract class is separated from the implementation.

```dart
/// package A
abstract class A{}

/// package B
@Singleton(as: Service)
class B implements A{}

/// root
final sl = GetIt.instance;

@InjectableInit(
  externalPackageModulesBefore: [
    ExternalModule(B),
  ],
)
Future<void> configureDependencies() => sl.init();


class C {
  final A a;
  C(this.a);
}
```

**Comment by Milad-Akarie** [comment]
Fixed in injectable_generator: 2.1.4

**Comment by mashahbazi** [comment]
Still facing same issue after upgrading to 2.1.4

**Comment by song011794** [comment]
build_runner: ^2.4.13
injectable: ^2.5.0
injectable_generator: ^2.6.2

I am using the above version but still have the same problem.
