### ISSUE TITLE
Error: The argument type 'EnvDevelopment Function()' can't be assigned to the parameter type 'Env'

### ISSUE THREAD

**Issue by mustafahimi** [Milad-Akarie/injectable#435]
Hi. after updating package to 2.3.3 i get this error:
Error: The argument type 'EnvDevelopment Function()' can't be assigned to the parameter type 'Env'

This is my EnvDevelopment class:

```
import 'package:clasor/src/core/environment/env.dart';
import 'package:flutter/cupertino.dart';
import 'package:injectable/injectable.dart';

@Singleton(as: Env, env: [AppEnvironment.development])
class EnvDevelopment extends Env {
  @override
  String get baseUrl => 'http://clasor-server-acl.sakkupardis.ir:5000/v1/';

  @override
  String get authWebViewUrl =>
      'http://sso-sandbox.pod.ir/oauth2/authorize/index.html?client_id=$clientId&response_type=code&redirect_uri=$signinUrl&scope=profile+social_write+social';

  @override
  String get signinUrl => 'http://clasor-client.sakkupardis.ir/signin';

  @override
  String get podSpaceUrl => 'https://sandbox.podspace.ir:8443/';

  @override
  String get excelEditorUrl => 'http://clasor-excel-editor.sakkupardis.ir/';

  @override
  String get wordEditorUrl => 'http://clasor-wordeditor.sakkupardis.ir/';

  @override
  String get flowchartEditorUrl =>
      'http://clasor-flowchart-editor.sakkupardis.ir/';

  @override
  String get podApiUrl => 'http://sandbox.sandpod.ir/';

  @override
  String get clientId => '18682629g64434d74b0004e8ecb3d3be1';

  @override
  String get userGroupHash => '4RBA2BBNRW349T';

  @override
  Locale get locale => const Locale('fa');
}
```

**Comment by Milad-Akarie** [comment]
@mustafahimi  2.3.4 should fix this issue.

**Comment by JoepHeijnen** [comment]
I am still having this issue on 2.4.1. It looks like this issue only happens when using `@Singleton`

For example:

```
@Singleton(env: [Environment.prod])
class OAuthIOSService extends OAuthService {}
```

Will be generated as:

```
gh.singleton<_i81.OAuthIOSService>(
  _i81.OAuthIOSService(),
  registerFor: {_prod},
);
```

The following code snippet fixes the issue
```
gh.singleton<_i81.OAuthIOSService>(
  () => _i81.OAuthIOSService(),
  registerFor: {_prod},
);
```
